CREATE TABLE IF NOT EXISTS public."Passenger"
(
    "PASSENGER_ID" serial NOT NULL,
    "PASSENGER_FIRSTN" character varying(255) NOT NULL,
    "PASSENGER_LASTN" character varying(255) NOT NULL,
    "PASSENGER_FATHERN" character varying(255) NOT NULL,
    "BIRTH_DT" character varying(255)NOT NULL,
    "PASSPORT_SERIES" integer NOT NULL,
    "PASSPORT_NUMBER" integer NOT NULL,
    "PASSENGER_CATEGORY" character varying(255),
    CONSTRAINT "Passenger_pkey" PRIMARY KEY ("PASSENGER_ID")
);


CREATE TABLE IF NOT EXISTS public."Airline"
(
    "OFFICE_ID" serial NOT NULL,
    "OFFICE_COUNTRY" character varying(255) NOT NULL,
    "OFFICE_CITY" character varying(255) NOT NULL,
    "OFFICE_STREET" character varying(255) NOT NULL,
    "OFFICE_HOUSE" character varying(255) NOT NULL,
    "PHONE_NUMBER" character varying(255) NOT NULL,
    CONSTRAINT "Airline_pkey" PRIMARY KEY ("OFFICE_ID")
);


CREATE TABLE IF NOT EXISTS public."Employee"
(
    "EMPLOYEE_ID" serial NOT NULL,
    "OFFICE_ID" integer NOT NULL,
    "CREW_FIRSTN" character varying(255) NOT NULL,
    "CREW_LASTN" character varying(255) NOT NULL,
    "CREW_FATHERN" character varying(255) NOT NULL,
    "BIRTH_DT" character varying(255) NOT NULL,
    "CREW_POSITION" character varying(255) NOT NULL,
    "WORK_EXPERIENCE" integer NOT NULL,
    "MEDICAL_EXAMINATION_DATE" character varying(255) NOT NULL,
    "CREW_STATUS" character varying(255) NOT NULL,
    CONSTRAINT "Employee_pkey" PRIMARY KEY ("EMPLOYEE_ID"),
    CONSTRAINT "OFFICE_ID" FOREIGN KEY ("OFFICE_ID")
        REFERENCES public."Airline" ("OFFICE_ID")
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS public."Airplane"
(
    "AIRPLANE_ID" serial NOT NULL,
    "OFFICE_ID" integer NOT NULL,
    "AIRPLANE_TYPE" character varying(255) NOT NULL,
    "AIRPLANE_CAPACITY" integer NOT NULL,
    "YEAR_OF_ISSUE" integer NOT NULL,
    "LAST_MAINTENANCE_DATE" character varying(255) NOT NULL,
    "AIRPLANE_STATUS" character varying(255) NOT NULL,
    "AIRPLANE_MILEAGE" integer NOT NULL,
    CONSTRAINT "Airplane_pkey" PRIMARY KEY ("AIRPLANE_ID"),
    CONSTRAINT "OFFICE_ID" FOREIGN KEY ("OFFICE_ID")
        REFERENCES public."Airline" ("OFFICE_ID") MATCH SIMPLE
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS public."Crew"
(
    "CREW_ID" serial NOT NULL,
    "OFFICE_ID" integer NOT NULL,
    "AIRPLANE_ID" integer NOT NULL,
    "SHIP_COMMANDER" integer NOT NULL,
    "SECOND_PILOT" integer NOT NULL,
    "SENIOR_FLIGHT_ATTENDANT" integer NOT NULL,
    "FLIGHT_ATTENDANT_1" integer NOT NULL,
    "FLIGHT_ATTENDANT_2" integer NOT NULL,
    "FLIGHT_ATTENDANT_3" integer NOT NULL,
    "FLIGHT_ATTENDANT_4" integer NOT NULL,
    CONSTRAINT "Crew_pkey" PRIMARY KEY ("CREW_ID"),
    CONSTRAINT "AIRPLANE_ID" FOREIGN KEY ("AIRPLANE_ID")
        REFERENCES public."Airplane" ("AIRPLANE_ID")
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT "FLIGHT_ATTENDANT_1" FOREIGN KEY ("FLIGHT_ATTENDANT_1")
        REFERENCES public."Employee" ("EMPLOYEE_ID")
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT "FLIGHT_ATTENDANT_2" FOREIGN KEY ("FLIGHT_ATTENDANT_2")
        REFERENCES public."Employee" ("EMPLOYEE_ID")
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT "FLIGHT_ATTENDANT_3" FOREIGN KEY ("FLIGHT_ATTENDANT_3")
        REFERENCES public."Employee" ("EMPLOYEE_ID")
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT "FLIGHT_ATTENDANT_4" FOREIGN KEY ("FLIGHT_ATTENDANT_4")
        REFERENCES public."Employee" ("EMPLOYEE_ID")
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT "OFFICE_ID" FOREIGN KEY ("OFFICE_ID")
        REFERENCES public."Airline" ("OFFICE_ID")
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT "SECOND_PILOT" FOREIGN KEY ("SECOND_PILOT")
        REFERENCES public."Employee" ("EMPLOYEE_ID")
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT "SENIOR_FLIGHT_ATTENDANT" FOREIGN KEY ("SENIOR_FLIGHT_ATTENDANT")
        REFERENCES public."Employee" ("EMPLOYEE_ID")
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT "SHIP_COMMANDER" FOREIGN KEY ("SHIP_COMMANDER")
        REFERENCES public."Employee" ("EMPLOYEE_ID")
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS public."Airport"
(
    "AIRPORT_ID" serial NOT NULL,
    "AIRPORT_NAME" character varying(255) NOT NULL,
    "AIRPORT_CITY" character varying(255) NOT NULL,
    "AIRPORT_COUNTRY" character varying(255) NOT NULL,
    "NUMBER_OF_RUNWAYS" integer NOT NULL,
    "AIRPORT_CAPACITY" integer NOT NULL,
    "AIRPORT_TYPE" character varying(255) NOT NULL,
    "WORKING_HOURS" character varying(255) NOT NULL,
    CONSTRAINT "Airport_pkey" PRIMARY KEY ("AIRPORT_ID")
);


CREATE TABLE IF NOT EXISTS public."Flight"
(
    "FLIGHT_ID" serial NOT NULL,
    "OFFICE_ID" integer NOT NULL,
    "AIRPLANE_ID" integer NOT NULL,
    "DEPARTURE_AIRPORT" integer NOT NULL,
    "ARRIVAL_AIRPORT" integer NOT NULL,
    "DEPARTURE_DTTM" character varying(255) NOT NULL,
    "ARRIVAL_DTTM" character varying(255) NOT NULL,
    "TRAVEL_TIME" integer NOT NULL,
    "FLIGHT_STATUS" character varying(255) NOT NULL,
    "VALID_FROM_DTTM" character varying(255) DEFAULT '1970-01-01 00:00:00'::character varying,
    "VALID_TO_DTTM" character varying(255) DEFAULT '5999-01-01 00:00:00'::character varying,
    CONSTRAINT "Flight_pkey" PRIMARY KEY ("FLIGHT_ID"),
    CONSTRAINT "AIRPLANE_ID" FOREIGN KEY ("AIRPLANE_ID")
        REFERENCES public."Airplane" ("AIRPLANE_ID")
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT "ARRIVAL_AIRPORT" FOREIGN KEY ("ARRIVAL_AIRPORT")
        REFERENCES public."Airport" ("AIRPORT_ID")
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT "DEPARTURE_AIRPORT" FOREIGN KEY ("DEPARTURE_AIRPORT")
        REFERENCES public."Airport" ("AIRPORT_ID")
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT "OFFICE_ID" FOREIGN KEY ("OFFICE_ID")
        REFERENCES public."Airline" ("OFFICE_ID")
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS public."Loyalty_card"
(
    "LOYALTY_CARD_ID" serial NOT NULL,
    "PASSENGER_ID" integer NOT NULL,
    "LOYALTY_LEVEL" character varying(255) NOT NULL,
    "LOYALTY_POINTS" integer NOT NULL,
    "CARD_STATUS" character varying(255) NOT NULL,
    CONSTRAINT "Loyalty_card_pkey" PRIMARY KEY ("LOYALTY_CARD_ID"),
    CONSTRAINT "PASSENGER_ID" FOREIGN KEY ("PASSENGER_ID")
        REFERENCES public."Passenger" ("PASSENGER_ID")
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS public."Ticket"
(
    "TICKET_ID" serial NOT NULL,
    "PASSENGER_ID" integer NOT NULL,
    "FLIGHT_ID" integer NOT NULL,
    "PLACE_NUMBER" character varying(255) NOT NULL,
    "SERVICE_CLASS" character varying(255) NOT NULL,
    "TICKET_PRICE" character varying(255) NOT NULL,
    "STATUS_STATUS" character varying(255) NOT NULL,
    CONSTRAINT "Ticket_pkey" PRIMARY KEY ("TICKET_ID"),
    CONSTRAINT "FLIGHT_ID" FOREIGN KEY ("FLIGHT_ID")
        REFERENCES public."Flight" ("FLIGHT_ID")
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT "PASSENGER_ID" FOREIGN KEY ("PASSENGER_ID")
        REFERENCES public."Passenger" ("PASSENGER_ID")
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS public."Payment"
(
    "PAYMENT_ID" serial NOT NULL,
    "PASSENGER_ID" integer NOT NULL,
    "TICKET_ID" integer NOT NULL,
    "LOYALTY_CARD_ID" integer NOT NULL,
    "PAYMENT_AMOUNT" integer NOT NULL,
    "PAYMENT_METHOD" character varying(255) NOT NULL,
    "PAYMENT_DTTM" character varying(255) DEFAULT '1970-01-01 00:00:00'::character varying,
    "PAYMENT_STATUS" character varying(255) NOT NULL,
    CONSTRAINT "Payment_pkey" PRIMARY KEY ("PAYMENT_ID"),
    CONSTRAINT "LOYALTY_CARD_ID" FOREIGN KEY ("LOYALTY_CARD_ID")
        REFERENCES public."Loyalty_card" ("LOYALTY_CARD_ID")
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT "PASSENGER_ID" FOREIGN KEY ("PASSENGER_ID")
        REFERENCES public."Passenger" ("PASSENGER_ID")
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT "TICKET_ID" FOREIGN KEY ("TICKET_ID")
        REFERENCES public."Ticket" ("TICKET_ID")
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
);